name: Trigger publish workflow
env:
  GH_USERNAME: baolongdev
  GH_REPONAME: AR_Advertisement 
  WORKFLOW_FILE: publish.yml
on:
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Vercel
        uses: amondnet/vercel-action@v20
        with:
          # TODO: Update Github Secrets with values
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }} # Required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} # Required
          vercel-args: "--prod" #Optional